import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React, { useState, useEffect } from 'react';
import { connectWallet, checkWalletConnection } from '../services/connectWallet';

export default function Home() {

  useEffect(() => {
    connectWallet();
  }, []);


  const [liveAccount, setLiveAccount] = useState();
  
  const [message, setMessage] = useState();

  const [name, setName] = useState();

  const [allCakes, setAllCakes] = useState();

  const buyCake = async () => {
    try {
      const { ethereum } = window;
      if(ethereum) {
        
      }
    } catch(error) {

    }
  }

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Cake Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Cake Board</a>
        </h1>
        <button class="btn btn-primary">Connect Wallet</button>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
