import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, { useState, useEffect } from 'react';
import { connectWallet, checkWalletConnection } from '../services/connectWallet';
import { buyCake, getCakes } from '../services/contract';
export default function Home() {

  useEffect(() => {
    checkWalletConnection();
  }, []);


  const [liveAccount, setLiveAccount] = useState();
  const [message, setMessage] = useState();
  const [name, setName] = useState();
  const [allCakes, setAllCakes] = useState();
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Cake Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Cake Board</a>
        </h1>
        <button className="btn btn-primary" onClick={ connectWallet }>Connect Wallet</button>
        <button className='btn btn-success' onClick={ buyCake }>Buy Cake</button>
        <button className='btn btn-danger' onClick={ getCakes }>Get Cakes</button>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
